edition = "2021"
combine_control_expr = false
enum_discrim_align_threshold = 60
format_macro_matchers = true
newline_style = "Unix"
normalize_doc_attributes = true
reorder_impl_items = true
# imports
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
# comments
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true