[package]
name = "poem-openapi-response"
version = "0.1.0"
edition = "2021"
authors = ["zihan <ZihanType@proton.me>"]
description = "Define uniform response for Poem OpenAPI."
keywords = ["poem", "open-api", "response", "swagger"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poem = { version = "1.3.30", default-features = false }
poem-openapi = { version = "2.0.0-alpha.4", default-features = false }
