[package]
name = "poem-openapi-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poem = { version = "1.3.30", default-features = false }
poem-openapi = { version = "2.0.0", features = ["swagger-ui"] }
poem-openapi-response = { path = "../poem-openapi-response" }
poem-openapi-api-derive = { path = "../poem-openapi-api-derive" }
tokio = { version = "1", features = ["full"] }
